[project]
src = "contracts"
out = "out"
dot_env = ".env"

# Anvil network configuration
[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337
default_account_name = "$DEFAULT_ACCOUNT_NAME"
unsafe_password_file = "$UNSAFE_PASSWORD_FILE"

[networks.anvil.contracts]
counter = { address = "0x5FbDB2315678afecb367f032d93F642f64180aa3", deploy = "sript/deploy.py" }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
