[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=1.5.0",
    "moccasin>=0.4.2",
    "natrix==0.1.8",
    "vyper==0.4.2",
    "web3>=7.12.0",
]
